"""initial schema

Revision ID: 1c3b55347cb1
Revises: 
Create Date: 2025-09-18 17:48:08.473344

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c3b55347cb1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('filieres',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom_filiere', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nom_filiere')
    )
    op.create_table('matieres',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom_matiere', sa.String(length=100), nullable=False),
    sa.Column('code_matiere', sa.String(length=20), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code_matiere')
    )
    op.create_table('niveaux',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom_niveau', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nom_niveau')
    )
    op.create_table('salles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom_salle', sa.String(length=50), nullable=False),
    sa.Column('capacite', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nom_salle')
    )
    op.create_table('groupes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom_groupe', sa.String(length=50), nullable=False),
    sa.Column('filiere_id', sa.Integer(), nullable=False),
    sa.Column('niveau_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['filiere_id'], ['filieres.id'], ),
    sa.ForeignKeyConstraint(['niveau_id'], ['niveaux.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nom_groupe', 'filiere_id', 'niveau_id', name='_nom_groupe_filiere_niveau_uc')
    )
    op.create_table('utilisateurs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=100), nullable=False),
    sa.Column('prenom', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('mot_de_passe_hash', sa.String(length=128), nullable=False),
    sa.Column('role', sa.Enum('ETUDIANT', 'ENSEIGNANT', 'ADMINISTRATEUR', name='role_enum_type', native_enum=False), nullable=False),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.Column('picture', sa.String(length=20), nullable=False),
    sa.Column('groupe_id', sa.Integer(), nullable=True),
    sa.Column('filiere_id', sa.Integer(), nullable=True),
    sa.Column('niveau_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['filiere_id'], ['filieres.id'], ),
    sa.ForeignKeyConstraint(['groupe_id'], ['groupes.id'], ),
    sa.ForeignKeyConstraint(['niveau_id'], ['niveaux.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('utilisateurs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_utilisateurs_email'), ['email'], unique=True)

    op.create_table('conversations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('participant1_id', sa.Integer(), nullable=False),
    sa.Column('participant2_id', sa.Integer(), nullable=False),
    sa.Column('last_message_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['participant1_id'], ['utilisateurs.id'], ),
    sa.ForeignKeyConstraint(['participant2_id'], ['utilisateurs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('participant1_id', 'participant2_id', name='_conversation_participants_uc')
    )
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_conversations_last_message_time'), ['last_message_time'], unique=False)

    op.create_table('cours',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('matiere_id', sa.Integer(), nullable=False),
    sa.Column('enseignant_id', sa.Integer(), nullable=False),
    sa.Column('salle_id', sa.Integer(), nullable=False),
    sa.Column('date_cours', sa.Date(), nullable=False),
    sa.Column('heure_debut', sa.Time(), nullable=False),
    sa.Column('heure_fin', sa.Time(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['enseignant_id'], ['utilisateurs.id'], ),
    sa.ForeignKeyConstraint(['matiere_id'], ['matieres.id'], ),
    sa.ForeignKeyConstraint(['salle_id'], ['salles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('disponibilites_enseignants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('enseignant_id', sa.Integer(), nullable=False),
    sa.Column('jour_semaine', sa.Enum('Lundi', 'Mardi', 'Mercredi', 'Jeudi', 'Vendredi', 'Samedi', name='jour_semaine_enum', native_enum=False), nullable=False),
    sa.Column('heure_debut', sa.Time(), nullable=False),
    sa.Column('heure_fin', sa.Time(), nullable=False),
    sa.ForeignKeyConstraint(['enseignant_id'], ['utilisateurs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('enseignant_id', 'jour_semaine', 'heure_debut', name='_enseignant_dispo_uc')
    )
    op.create_table('enseigne',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('enseignant_id', sa.Integer(), nullable=False),
    sa.Column('matiere_id', sa.Integer(), nullable=False),
    sa.Column('filiere_id', sa.Integer(), nullable=False),
    sa.Column('niveau_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['enseignant_id'], ['utilisateurs.id'], ),
    sa.ForeignKeyConstraint(['filiere_id'], ['filieres.id'], ),
    sa.ForeignKeyConstraint(['matiere_id'], ['matieres.id'], ),
    sa.ForeignKeyConstraint(['niveau_id'], ['niveaux.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('enseignant_id', 'matiere_id', 'filiere_id', 'niveau_id', name='_enseignant_matiere_filiere_niveau_uc')
    )
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titre', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('date_creation', sa.DateTime(), nullable=False),
    sa.Column('destinataire_role', sa.Enum('ETUDIANT', 'ENSEIGNANT', 'ADMINISTRATEUR', 'ALL', name='destinataire_role_enum_type', native_enum=False), nullable=False),
    sa.Column('destinataire_id', sa.Integer(), nullable=True),
    sa.Column('est_lue', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['destinataire_id'], ['utilisateurs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('push_subscriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('subscription_json', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['utilisateurs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cours_affectations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cours_id', sa.Integer(), nullable=False),
    sa.Column('filiere_id', sa.Integer(), nullable=True),
    sa.Column('niveau_id', sa.Integer(), nullable=True),
    sa.Column('groupe_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cours_id'], ['cours.id'], ),
    sa.ForeignKeyConstraint(['filiere_id'], ['filieres.id'], ),
    sa.ForeignKeyConstraint(['groupe_id'], ['groupes.id'], ),
    sa.ForeignKeyConstraint(['niveau_id'], ['niveaux.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('image_url', sa.String(length=255), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.CheckConstraint('body IS NOT NULL OR image_url IS NOT NULL', name='_message_content_check'),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['utilisateurs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_messages_timestamp'), ['timestamp'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_messages_timestamp'))

    op.drop_table('messages')
    op.drop_table('cours_affectations')
    op.drop_table('push_subscriptions')
    op.drop_table('notifications')
    op.drop_table('enseigne')
    op.drop_table('disponibilites_enseignants')
    op.drop_table('cours')
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_conversations_last_message_time'))

    op.drop_table('conversations')
    with op.batch_alter_table('utilisateurs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_utilisateurs_email'))

    op.drop_table('utilisateurs')
    op.drop_table('groupes')
    op.drop_table('salles')
    op.drop_table('niveaux')
    op.drop_table('matieres')
    op.drop_table('filieres')
    # ### end Alembic commands ###
